apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../helm/cilium/repository.yaml
  - release.yaml
configMapGenerator:
  - name: cilium-values
    namespace: kube-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
