apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cilium-test
  namespace: default
  labels:
    app: nginx-cilium-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-cilium-test
  template:
    metadata:
      labels:
        app: nginx-cilium-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cilium-lb
  namespace: default
  labels:
    app: nginx-cilium-test
    ip-pool: default-pool
spec:
  type: LoadBalancer
  selector:
    app: nginx-cilium-test
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
