k8sServiceHost: 10.10.0.95
k8sServicePort: 6443
cluster:
  name: default
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.42.0.0/16
kubeProxyReplacement: true
routingMode: tunnel
tunnelProtocol: vxlan
operator:
  replicas: 1
l2announcements:
  enabled: true
l2NeighDiscovery:
  enabled: true
ipv4NativeRoutingCIDR: 10.10.0.0/24
