apiVersion: v1
kind: Service
metadata:
  name: nginx-test-lb
  namespace: metallb-system
  annotations:
    metallb.io/address-pool: inf-monitoring-pool
spec:
  type: LoadBalancer
  selector:
    app: nginx-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: None
  externalTrafficPolicy: Cluster
