---
- name: Render K3s agent config.yaml from host-specific template
  ansible.builtin.template:
    src: "{{ k3s_config_template }}"
    dest: "/etc/rancher/k3s/config.yaml"
    mode: '0644'
  notify: Restart k3s agent

- name: Check if k3s agent service exists
  ansible.builtin.stat:
    path: /etc/systemd/system/k3s-agent.service
  register: k3s_agent_service

- name: Install k3s agent
  ansible.builtin.command: sh {{ k3s_install_script_path }} agent
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: "{{ 'true' if k3s_install_skip_download else 'false' }}"
  when: not k3s_agent_service.stat.exists

- name: Enable and start k3s agent
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started

